[tool.poetry]
name = "volumerize"
package-mode = false

[tool.poetry.dependencies]
apprise = "^1.7.4"
azure-storage-blob = "^12.19.1"
b2sdk = "^1.32.0"
boto = "^2.49.0"
boto3 = "^1.34.59"
boxsdk = {extras = ["jwt"], version = "^3.9.2"}
dropbox = "^11.36.2"
duplicity = "^2.2.2"
fasteners = "^0.19"
gdata-python3 = "^3.0.1"
google-api-python-client = "^2.121.0"
google-auth-oauthlib = "^1.2.0"
jottalib = "^0.5.1"
mediafire = "^0.6.1"
megatools = "^0.0.4"
paramiko = "^3.4.0"
packaging = "21.3"
pexpect = "^4.9.0"
psutil = "^5.9.8"
pycrypto = "^2.6.1"
pydrive2 = "^1.19.0"
python = "^3.10"
python-keystoneclient = "^5.4.0"
python-swiftclient = "^4.5.0"

# Incompatible packages
# pyrax

[build-system]
requires = ["poetry-core>=1.8.2"]
build-backend = "poetry.core.masonry.api"
