version: 2.1

commands:
  install_deps:
    description: "Install Dependencies"
    steps:
      - run:
          name: Initialize Submodules
          command: |
            git submodule init &&
            git submodule update --remote
  build_images:
    description: "Builds Docker Images"
    steps:
      - run:
          name: Build Images
          command: |
            set +o pipefail
            ./buildscripts/buildSupportedAlpineImages.sh
  test_images:
    description: "Test Images"
    steps:
      - run:
          name: Test Images
          command: |
              ./buildscripts/testSupportedAlpineImages.sh
      - store_artifacts:
          path: report
      - store_test_results:
          path: report
  push_images:
    description: "Push Image to DockerHub"
    steps:
      - run:
          name: Push Images to DockerHub
          command: |
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              ./buildscripts/releaseSupportedAlpineImages.sh

jobs:
  build_branch:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - install_deps
      - build_images
      - test_images

  build_master:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - install_deps
      - build_images
      - test_images
      - push_images

  build_nightly:
    environment:
      IMAGE_VERSION: nightly
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - install_deps
      - build_images
      - test_images
      - push_images

  build_tags:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - install_deps
      - build_images
      - test_images
      - push_images

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build_tags:
          filters:
            tags:
              only: /^\d+(\.\d+)+$/
            branches:
              ignore: /.*/
      - build_master:
          filters:
            branches:
              only: master
      - build_branch:
          filters:
            branches:
              only: /.*/
              ignore: master
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_nightly
